app = 'life-organizer-bot'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_PATH = '/data/food_places.db'

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
